# -*- coding: utf-8 -*-
"""explorandoDeadCells.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ct47cV2MJqsYoOVE5EuoUAm7YPU9zCeb
"""

import streamlit as st
import pandas as pd

# Download do primeiro csv (trilha)
trilhaUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/trilha-dead-cells.csv"

# Download do segundo csv (time series)
temporalUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/timeseries-dead-Cells.csv"

# Download do terceiro csv (gear data)
gearUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/gear-dead-cells.csv"

df_geral = pd.read_csv(trilhaUrl, sep=",", header="infer")
df_gear = pd.read_csv(gearUrl, sep=",", header="infer")
df_temporal = pd.read_csv(temporalUrl, sep=",", header="infer")

st.title("Análise Simples: Armas utilizadas e Série Temporal de uma Corrida")

if st.checkbox('Show General Data'):
    st.subheader('Dados Gerais de Gameplay')
    st.write(df_geral)

if st.checkbox('Show Gear Data'):
    st.subheader('Dados de possíveis equipamentos no Jogo')
    st.write(df_gear)

if st.checkbox('Show Time Data'):
    st.subheader('Dados temporais Brutos')
    st.write(df_temporal)

st.header("Equipamentos utilizados naquela luta contra tal... chefe!!")

st.subheader("Escolha qual luta contra o chefe e escolha qual o resultado")
filtro_boss = st.selectbox("Choose one Boss..", ("beatConcierge?", "beatConjuntivictus?", "beatMotherFlea?", "beatTimeGuardian?", "beatGiant?", "beatHandofTheKing?"))
sr.write(filtro_boss)
filtro_result = st.slider("You Win(1) or You Died(0)?", 0, 1, 0)

dfBar = df_geral[df_geral[filtro_boss] == filtro_result]

# Monta 4 tipos de dataframe com o agrupamento dos equipamentos mais utilizados

df01 = dfBar["gear01"].value_counts()
df02 = dfBar["gear02"].value_counts()
df03 = dfBar["gear03"].value_counts()
df04 = dfBar["gear04"].value_counts()

# Apresenta os equipamentos em gráficos de barra

st.subheader('Equipamento Primário 1')
st.bar_chart(df01)

st.subheader('Equipamento Primário 2')
st.bar_chart(df02)

st.subheader('Equipamento Secundário 1')
st.bar_chart(df03)

st.subheader('Equipamento Secundário 2')
st.bar_chart(df04)

st.header("Dados Gerais (em construção)")

st.subheader("A Morte Percorre esses Muros...")
chartDungeon = df_geral["lastDungeon"].value_counts()
st.bar_chart(chartDungeon)

st.subheader('Top 5 Quanto mais...melhor!!')
chartStatus = df_geral["totalScrolls"].sort_values()
st.table(chartStatus.head(5))

st.subheader('Troca troca de armas...')
chartWeapon = df_temporal[['time', 'gear01', 'gear02', 'gear03', 'gear04']]
st.line_chart(chartWeapon)

st.header("Time Series Data")

st.subheader('Como o Status cresce com o tempo...')
chartData = df_temporal[['time', 'brutality', 'tactical', 'survivor']]
st.line_chart(chartData)

st.subheader('Quantidade de pergaminhos de acordo com o tempo')
chartscroll = df_temporal[['time', 'scroll_cylinder']]
st.line_chart(chartscroll)
