# -*- coding: utf-8 -*-
"""explorandoDeadCells.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ct47cV2MJqsYoOVE5EuoUAm7YPU9zCeb
"""

import streamlit as st
import pandas as pd

# Download do primeiro csv (trilha)
trilhaUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/trilha-dead-cells.csv"

# Download do segundo csv (time series)
temporalUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/timeseries-dead-Cells.csv"

# Download do terceiro csv (gear data)
gearUrl = "https://raw.githubusercontent.com/Alexno9/gameplay-deadcells-analysis/master/gear-dead-cells.csv"

df_geral = pd.read_csv(trilhaUrl, sep=",", header="infer")
df_gear = pd.read_csv(gearUrl, sep=",", header="infer")
df_temporal = pd.read_csv(temporalUrl, sep=",", header="infer")

st.title("Análise Simples: Armas utilizadas e Série Temporal de uma Corrida")

if st.checkbox('Show General Data'):
    st.subheader('Dados Gerais de Gameplay')
    st.write(df_geral)

if st.checkbox('Show Gear Data'):
    st.subheader('Dados de possíveis equipamentos no Jogo')
    st.write(df_gear)

if st.checkbox('Show Time Data'):
    st.subheader('Dados temporais Brutos')
    st.write(df_temporal)

st.header("Equipamentos utilizados contra Concierge, Time Guardian e Hand of The King!!")
filtro_result = st.slider("You Win(1) or You Died(0)?", 0, 1, 0)

dfBossA = df_geral[df_geral["beatConcierge?"] == filtro_result]
dfBossB = df_geral[df_geral["beatTimeGuardian?"] == filtro_result]
dfBossC = df_geral[df_geral["beatHandOfTheKing?"] == filtro_result]

# Monta 4 tipos de dataframe com o agrupamento dos equipamentos mais utilizados

df01 = dfBossA["gear01"].value_counts()
df02 = dfBossA["gear02"].value_counts()
df03 = dfBossA["gear03"].value_counts()
df04 = dfBossA["gear04"].value_counts()

df05 = dfBossB["gear01"].value_counts()
df06 = dfBossB["gear02"].value_counts()
df07 = dfBossB["gear03"].value_counts()
df08 = dfBossB["gear04"].value_counts()

df09 = dfBossC["gear01"].value_counts()
df10 = dfBossC["gear02"].value_counts()
df11 = dfBossC["gear03"].value_counts()
df12 = dfBossC["gear04"].value_counts()

# Apresenta os equipamentos em gráficos de barra

st.header('Concierge')
st.subheader('Armas')
st.bar_chart(df01)
st.bar_chart(df02)

st.subheader('Habilidades')
st.bar_chart(df03)
st.bar_chart(df04)

st.header('Time Guardian')
st.subheader('Armas')
st.bar_chart(df05)
st.bar_chart(df06)

st.subheader('Habilidades')
st.bar_chart(df07)
st.bar_chart(df08)

st.header('Hand Of The King')
st.subheader('Armas')
st.bar_chart(df09)
st.bar_chart(df10)

st.subheader('Habilidades')
st.bar_chart(df11)
st.bar_chart(df12)

st.header("Dados Gerais (em construção)")

st.subheader("A Morte Percorre esses Muros...")
chartDungeon = df_geral["lastDungeon"].value_counts()
st.bar_chart(chartDungeon)

st.subheader('Morreu...Que pena...Quantos pergaminhos mesmo?')
chartStatus = df_geral.groupby("lastDungeon").mean()[["totalScrolls"]]
st.table(chartStatus)

st.header("Time Series Data")

st.subheader('Como o Status cresce com o tempo...')
chartData = df_temporal[['time', 'brutality', 'tactical', 'survivor']]
st.line_chart(chartData)

st.subheader('Quantidade de pergaminhos de acordo com o tempo')
chartscroll = df_temporal[['time', 'scroll_cylinder']]
st.line_chart(chartscroll)